### ISSUE TITLE
Test Flake

### ISSUE THREAD

**Issue by braughtg** [FarmData2/FarmData2#72]
Note tests that flake and the number of times that they have been seen here.  Items will appear in ~~strikethrough~~ when an attempt has been made to fix the flake. If the test flakes again the ~~strikethrough~~ will be removed.

Keep the list in alphabetical order.

- `cover_crop_seeding.seedApplicationEquipment.e2e.cy.js` - Cover Crop Seeding: Seed Application Equipment Component - 1
- `cover_crop_seeding.seedApplicationEquipment.e2e.cy.js` - Cover Crop Seeding: Seed Incorporation Equipment Component - 1
- ~~`DateSelector.behavior.comp.cy.js` - 1~~
- ~~`farmosUtil.crops.unit.cy.js` - Test that getCrops uses session storage cache - 1~~
- ~~`getFarmOSInstance` - Clear everything - 3~~
- `soil_disturbance/lib.submit.unit.cy.js` - 4 - "after all" hook failing
- `soil_disturbance.equipment.e2e.cy.sj` - Soil Disturbance: Equipment Component -4

**Comment by braughtg** [comment]
By having any `it` with an `intercept` include `{ retries: 4 }` seems to significantly address the flake that appears to go with `cy.intercept`.

**Comment by RolandLocke** [comment]
Also having some issues with `soil_disturbance.equipment.e2e.cy.sj `. I'm seeing the test fail while running `runAllTests`, but will pass when run individually on either Electron or Firefox.

**Comment by braughtg** [comment]
`soil_disturbance.equipment.e2e.cy.sj` - Soil Disturbance: Equipment Component 

```
  1) Soil Disturbance: Equipment Component
       Updating beds updates area:
     CypressError: `cy.check()` failed because this element is not visible:
`<input id="picklist-checkbox-0" data-cy="picklist-checkbox-0" class="form-check-input" type="checkbox" name="picklist-checkbox-0" value="true" checked="">`
This element `<input#picklist-checkbox-0.form-check-input>` is not visible because it has CSS property: `position: fixed` and it's being covered by another element:
`<span id="termination-event-label" data-cy="termination-event-label">Termina...</span>`
Fix this problem, or use `{force: true}` to disable error checking.
https://on.cypress.io/element-cannot-be-interacted-with
```

**Comment by braughtg** [comment]
`cover_crop_seeding.seedApplicationEquipment.e2e.cy.js` - Cover Crop Seeding: Seed Application Equipment Component
`cover_crop_seeding.seedApplicationEquipment.e2e.cy.js` - Cover Crop Seeding: Seed Incorporation Equipment Component

```
 1) Cover Crop Seeding: Seed Application Equipment Component
       Proper numeric fields appear when equipment is selected:
     AssertionError: Timed out retrying after 10000ms: Expected <div#soil-disturbance-passes> not to exist in the DOM, but it was continuously found.
      at Context.eval (http://farmos/__cypress/tests?p=src/entrypoints/cover_crop_seeding/cover_crop_seeding.seedApplicationEquipment.e2e.cy.js:65:9)

  (Results)
  Running:  cover_crop_seeding/cover_crop_seeding.seedIncorporationEquipment.e2e          (20 of 55)
            .cy.js                                                                                  
  1 failing
  1) Cover Crop Seeding: Seed Incorporation Equipment Component
       Proper numeric fields appear when equipment is selected:
     AssertionError: Timed out retrying after 10000ms: Expected <div#soil-disturbance-passes> not to exist in the DOM, but it was continuously found.
      at Context.eval (http://farmos/__cypress/tests?p=src/entrypoints/cover_crop_seeding/cover_crop_seeding.seedIncorporationEquipment.e2e.cy.js:65:9)
```
